"""VK Teams Async Bot -- async Python library for VK Teams Bot API."""

try:
    from importlib.metadata import version as _get_version

    __version__ = _get_version("vk-teams-async-bot")
except Exception:
    __version__ = "0.0.0"

from .bot import Bot
from .dispatcher import Dispatcher
from .errors import (
    APIError,
    EventParsingError,
    NetworkError,
    PollingError,
    RateLimitError,
    ServerError,
    SessionError,
    TimeoutError,
    VKTeamsError,
)
from .filters import (
    CallbackDataFilter,
    CallbackDataRegexpFilter,
    ChatIdFilter,
    ChatTypeFilter,
    CommandFilter,
    FileFilter,
    FileTypeFilter,
    FilterBase,
    ForwardFilter,
    FromUserFilter,
    MentionFilter,
    MentionUserFilter,
    MessageFilter,
    MessageTextPartFromNickFilter,
    NotFilter,
    RegexpFilter,
    RegexpTextPartsFilter,
    ReplyFilter,
    StateFilter,
    StickerFilter,
    TagFilter,
    TextFilter,
    VoiceFilter,
)
from .fsm import BaseStorage, FSMContext, MemoryStorage, State, StatesGroup, StorageKey

try:
    from .fsm import RedisStorage
except ImportError:
    pass
from .handlers import (
    BaseHandler,
    CallbackQueryHandler,
    CommandHandler,
    DeletedMessageHandler,
    EditedMessageHandler,
    LeftChatMembersHandler,
    MessageHandler,
    NewChatMembersHandler,
    PinnedMessageHandler,
    UnpinnedMessageHandler,
)
from .middleware import BaseMiddleware, MiddlewareManager, SessionTimeoutMiddleware
from .types import (
    AdminsResponse,
    BaseEvent,
    BotInfo,
    CallbackQueryEvent,
    ChatAction,
    ChatCreateResponse,
    ChatInfoChannel,
    ChatInfoGroup,
    ChatInfoPrivate,
    ChatInfoResponse,
    ChatType,
    DeletedMessageEvent,
    EditedMessageEvent,
    Event,
    EventChatRef,
    EventType,
    FileInfo,
    FilePart,
    FileUploadResponse,
    Format,
    ForwardPart,
    InlineKeyboardMarkup,
    KeyboardButton,
    LeftChatMembersEvent,
    MembersResponse,
    MentionPart,
    MessagePart,
    MessageResponse,
    NestedMessage,
    NewChatMembersEvent,
    NewMessageEvent,
    OkResponse,
    OkWithDescriptionResponse,
    ParseMode,
    PartialSuccessResponse,
    Parts,
    PinnedMessageEvent,
    RawUnknownEvent,
    ReplyPart,
    StickerPart,
    Style,
    StyleKeyboard,
    StyleType,
    UnpinnedMessageEvent,
    User,
    UsersResponse,
    VoicePart,
    parse_event,
)

__all__ = [
    # core
    "__version__",
    "Bot",
    "Dispatcher",
    # errors
    "APIError",
    "EventParsingError",
    "NetworkError",
    "PollingError",
    "RateLimitError",
    "ServerError",
    "SessionError",
    "TimeoutError",
    "VKTeamsError",
    # filters
    "CallbackDataFilter",
    "CallbackDataRegexpFilter",
    "ChatIdFilter",
    "ChatTypeFilter",
    "CommandFilter",
    "FileFilter",
    "FileTypeFilter",
    "FilterBase",
    "ForwardFilter",
    "FromUserFilter",
    "MentionFilter",
    "MentionUserFilter",
    "MessageFilter",
    "MessageTextPartFromNickFilter",
    "NotFilter",
    "RegexpFilter",
    "RegexpTextPartsFilter",
    "ReplyFilter",
    "StateFilter",
    "StickerFilter",
    "TagFilter",
    "TextFilter",
    "VoiceFilter",
    # fsm
    "BaseStorage",
    "FSMContext",
    "MemoryStorage",
    "State",
    "StatesGroup",
    "RedisStorage",
    "StorageKey",
    # handlers
    "BaseHandler",
    "CallbackQueryHandler",
    "CommandHandler",
    "DeletedMessageHandler",
    "EditedMessageHandler",
    "LeftChatMembersHandler",
    "MessageHandler",
    "NewChatMembersHandler",
    "PinnedMessageHandler",
    "UnpinnedMessageHandler",
    # middleware
    "BaseMiddleware",
    "MiddlewareManager",
    "SessionTimeoutMiddleware",
    # types
    "AdminsResponse",
    "BaseEvent",
    "BotInfo",
    "CallbackQueryEvent",
    "ChatAction",
    "ChatCreateResponse",
    "ChatInfoChannel",
    "ChatInfoGroup",
    "ChatInfoPrivate",
    "ChatInfoResponse",
    "ChatType",
    "DeletedMessageEvent",
    "EditedMessageEvent",
    "Event",
    "EventChatRef",
    "EventType",
    "FileInfo",
    "FilePart",
    "FileUploadResponse",
    "Format",
    "ForwardPart",
    "InlineKeyboardMarkup",
    "KeyboardButton",
    "LeftChatMembersEvent",
    "MembersResponse",
    "MentionPart",
    "MessagePart",
    "MessageResponse",
    "NestedMessage",
    "NewChatMembersEvent",
    "NewMessageEvent",
    "OkResponse",
    "OkWithDescriptionResponse",
    "ParseMode",
    "PartialSuccessResponse",
    "Parts",
    "PinnedMessageEvent",
    "RawUnknownEvent",
    "ReplyPart",
    "StickerPart",
    "Style",
    "StyleKeyboard",
    "StyleType",
    "UnpinnedMessageEvent",
    "User",
    "UsersResponse",
    "VoicePart",
    "parse_event",
]
